services:
    sacrpkg_restapi.filter:
        class: sacrpkg\RestapiBundle\Model\Filter
        public: true
        arguments:
            - '@request_stack'


    sacrpkg\RestapiBundle\Model\Filter: '@sacrpkg_restapi.filter'
    
    sacrpkg_restapi.paginator:
        class: sacrpkg\RestapiBundle\Model\Paginator
        public: true
        arguments:
            - '@request_stack'


    sacrpkg\RestapiBundle\Model\Paginator: '@sacrpkg_restapi.paginator'
    
    sacrpkg_restapi.action_factory:
        class: sacrpkg\RestapiBundle\Model\Action\ActionFactory
        public: true
        arguments:
            - '@doctrine'
            - '@request_stack'
            - '@validator'

    
    sacrpkg\RestapiBundle\Model\Action\ActionFactoryInterface: '@sacrpkg_restapi.action_factory'